Import('compilerFlags')
env = Environment()
env.Append(CPPFLAGS = compilerFlags)

env.Append(CPPPATH = ["../website"])

sourceFiles = ["LiveFootballParser.cpp"]
objects = []

for sourceFile in sourceFiles:
    object = env.Object(source = sourceFile)
    objects.append(object)
      
Return("objects")