Import('compilerFlags')
env = Environment()
env.Append(CPPFLAGS = compilerFlags)

sourceFiles = ["HttpResponse.cpp", "CurlHttpHandler.cpp"]
objects = []

for sourceFile in sourceFiles:
    object = env.Object(source = sourceFile)
    objects.append(object)
      
Return("objects")



