Import('compilerFlags')
env = Environment()
env.Append(CPPFLAGS = compilerFlags)
env.Append(CPPPATH = ["../network"])

sourceFiles = ["LiveFootballHandler.cpp", "StreamingInfo.cpp"]
objects = []

for sourceFile in sourceFiles:
    object = env.Object(source = sourceFile)
    objects.append(object)
      
Return("objects")